# This workflow builds and publishes selected libraries

name: Publish to NPM

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - run: |
          # Make size check script executable
          chmod +x ../../scripts/check-file-size.sh
      - run: |
          # Run the size check script for clarity-js
          ../../scripts/check-file-size.sh clarity-js 0.8.0 "build/clarity.min.js" 5
      - run: |
          # Run the size check script for clarity-decode
          ../../scripts/check-file-size.sh clarity-decode 0.8.0 "build/clarity.decode.js" 5
      - run: |
          # Run the size check script for clarity-visualize
          ../../scripts/check-file-size.sh clarity-visualize 0.8.0 "build/clarity.visualize.js" 5

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: yarn build
      - run: npm publish
        working-directory: ./packages/rgaleev-local-package
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
      - run: npm publish
        working-directory: ./packages/rgaleev-local-package-dep
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
